# `Promise`链式编程

是异步编程的一种解决方案，以后只要有异步操作都可以直接封装到`new Promise`里面来。

通常进行网络请求的时候，我们封装的网络请求函数，因为不能立即拿到结果，所以不能像简单的`1+1=2`一样将结果返回。所以我们会传入另外一个函数，在数据请求成功的时候，将数据通过传入的函数回调出去。

![回调地域](D:\notes\Vue\img\15.Promise\回调地域.jpg)



什么情况下会使用`Promise`？

![定时器的异步事件](D:\notes\Vue\img\15.Promise\定时器的异步事件.jpg)

当我们进行异步操作的时候，会使用`Promise`对异步操作进行封装。

```js
// Promise接收的第一个参数是一个函数,该函数接收两个参数(resolve,reject),而这两个参数本身也是函数
new Promise((resolve, reject) => { 
   // 1.第一次发起网络请求 
   setTimeout(() => {
      // 成功的时候,调用resolve函数
      resolve() // 这里一旦调用了resolve函数,外面就会执行 .then 这个函数
   }, 1000)
}).then(() => { // .then 函数中又传入了一个函数
   // 1.第一次拿到结果的处理代码
   console.log('111')

   return new Promise((resolve, reject) => {
      // 2.第二次发起网络请求的代码
      setTimeout(() => {
         resolve() // 以后记住了,一旦写了resolve函数调用,外面就要跟上 .then()
      }, 1000)
   })
}).then(() => {

   // 2.第二次处理的代码
   console.log('222')
   return new Promise((resolve, reject) => {

      // 3.第三次网络请求的代码
      setTimeout(() => {
         resolve('sxw')
      }, 1000)
   })
}).then((data) => {

   // 3.第三次处理的代码
   console.log(data)
})
```

```js
new Promise((resolve, reject) => {
   setTimeout(() => {
      // 失败的时候,调用 reject, 并且错误信息通过 .catch() 函数进行捕获
      reject('error message')
   }, 1000)
}).catch((err) => {
   console.log(err)
})
```



# `Promise`的三种状态

当开发中有异步操作的时候，就可以给异步操作包装一个`Promise`对象。

异步操作之后会有三种状态：

- `pending`：等待状态，比如正在进行网络请求，或者定时器没有到时间
- `fulfill`：满足状态，当我们主动回调了`resolve`时，就处于该状态，并且会回调`.then()`
- `reject`：拒绝状态，当我们主动回调了`reject`时，就处于该状态，并且会回调`.catch()`

```js
// Promise的另外一种写法
new Promise((resolve,reject) => {
   setTimeout(() => {
      resolve('111')
      // reject('222')
   }, 1000)
}).then(data => {
   console.log(data)
}, err => {
   console.log(err)
})   
// .then(参数1,参数2) 其中参数1是成功时候会执行的回调,参数2是失败时候会执行的回调
```



# `Promise`链式调用

需求：先网络请求: `aaa` -> 自己处理，在处理：`aaa111` -> 自己处理，再处理：`aaa111222` -> 自己处理

```js
new Promise((resolve,reject) => {
   // 只在这里进行了异步操作
   setTimeout(() => {
      resolve('aaa')
   }, 1000)
}).then(res => {
   // 1.第一次自己处理
   console.log(res,'第一次自己处理')

   // 1.对结果进行第一次处理
   return new Promise((resolve,reject) => {
      resolve(res + '111')
   })
}).then(res => {
   // 2.第二次自己处理
   console.log(res, '第二次自己处理')

   // 2.对结果进行第二次处理
   return new Promise(resolve => {
      resolve(res + '222')
   })
}).then(res => {
   // 3.第三次自己处理
   console.log(res, '第三次自己处理')
}) 
```

对上述代码进行简化：

```js
new Promise((resolve,reject) => {
   // 只在这里进行了异步操作
   setTimeout(() => {
      resolve('aaa')
   }, 1000)
}).then(res => {
   // 1.第一次自己处理
   console.log(res,'第一次自己处理')

   // 1.对结果进行第一次处理
   return Promise.resolve(res + '111')
}).then(res => {
   // 2.第二次自己处理
   console.log(res, '第二次自己处理')

   // 2.对结果进行第二次处理
   return Promise.resolve(res + '222')
}).then(res => {
   // 3.第三次自己处理
   console.log(res, '第三次自己处理')
}) 
```

再次简化：

```js
// 省略掉Promise.resolve
new Promise((resolve,reject) => {
   // 只在这里进行了异步操作
   setTimeout(() => {
      resolve('aaa')
   }, 1000)
}).then(res => {
   // 1.第一次自己处理
   console.log(res,'第一次自己处理')

   // 1.对结果进行第一次处理
   return res + '111' // 这样子写的话,内部会自动使用Promise对其进行一次封装的
}).then(res => {
   // 2.第二次自己处理
   console.log(res, '第二次自己处理')

   // 2.对结果进行第二次处理
   return res + '222' 
}).then(res => {
   // 3.第三次自己处理
   console.log(res, '第三次自己处理')
}) 
```

如果有失败的情况：

```js
// 省略掉Promise.resolve
new Promise((resolve,reject) => {
   // 只在这里进行了异步操作
   setTimeout(() => {
      resolve('aaa')
   }, 1000)
}).then(res => {
   console.log(res,'第一次自己处理')

   // 对错误进行处理的简写
   return Promise.reject('error message')
   // throw 'error message' // 或者可以这样来抛出错误,并且也能够被catch捕获
}).then(res => {
   console.log(res, '第二次自己处理')
   return res + '222' 
}).then(res => {
   console.log(res, '第三次自己处理')
}) .catch(err => {
    console.log(err)
})
```



# `Promise`的`all`方法 

需求：某一个功能需要两次请求都完成的时候才能执行。

原始做法：

```js
// 定义两个flag
let isResult1 = false
let isResult2 = false

// 请求1: 
$.ajax({
   url: '',
   success: function() {
      console.log('结果1')
      isResult1 = true
      handleResult()
   }
})

// 请求2: 
$.ajax({
   url: '',
   success: function() {
      console.log('结果2')
      isResult2 = true
      handleResult()
   }
})

function handleResult() {
   if(isResult1 && isResult2) {
      // ...
   }
}
```

使用`Promise`的`all`方法解决：

```js
// 伪代码
Promise.all([
   new Promise((resolve,reject) => {
      $ajax({
         url: 'url1',
         success: function(data) {
            resolve(data)
         }
      })
   }),
   new Promise((resolve,reject) => {
      $ajax({
         url: 'url2',
         success: function(data) {
            resolve(data)
         }
      })
   }),
]).then(results => {
   console.log(results)
})  
```

```js
// 使用setTimeout进行简单的模拟
Promise.all([
   new Promise((resolve,reject) => {
      setTimeout(() => {
         resolve({name: 'sxw',age: 18})
      }, 3000)
   }),
   new Promise((resolve,reject) => {
      setTimeout(() => {
         resolve({name: 'kobe',age: 19})
      }, 2000)
   }),
]).then(results => {
   console.log(results)
})  
```

